import { Sparkles } from "lucide-react";
import { CATEGORY_META } from "@/lib/scoring";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Icon } from "@/components/icon";

export interface RecommendationView {
  id: string;
  category: string;
  title: string;
  problem: string;
  evidence: string;
  recommendation: string;
  priority: string;
  impact: string;
  effort: string;
  roadmap: string | null;
  beforeText: string | null;
  afterText: string | null;
  rationale: string | null;
}

const PRIORITY_RANK: Record<string, number> = {
  CRITICAL: 0,
  HIGH: 1,
  MEDIUM: 2,
  LOW: 3,
};

const PRIORITY_VARIANT: Record<string, "critical" | "poor" | "warning" | "good"> = {
  CRITICAL: "critical",
  HIGH: "poor",
  MEDIUM: "warning",
  LOW: "good",
};

const ROADMAP_LABEL: Record<string, string> = {
  TODAY: "Do today",
  WEEK: "This week",
  MONTH: "This month",
};

const ROADMAP_ORDER = ["TODAY", "WEEK", "MONTH", "OTHER"] as const;

export function AIRecommendations({ items }: { items: RecommendationView[] }) {
  if (items.length === 0) return null;

  const groups = new Map<string, RecommendationView[]>();
  for (const it of items) {
    const bucket = it.roadmap && ROADMAP_LABEL[it.roadmap] ? it.roadmap : "OTHER";
    const list = groups.get(bucket) ?? [];
    list.push(it);
    groups.set(bucket, list);
  }
  for (const list of groups.values()) {
    list.sort((a, b) => (PRIORITY_RANK[a.priority] ?? 9) - (PRIORITY_RANK[b.priority] ?? 9));
  }

  return (
    <div className="mt-10">
      <div className="mb-1 flex items-center gap-2">
        <Sparkles className="size-5 text-primary" />
        <h2 className="text-xl font-semibold">AI recommendations</h2>
        <Badge variant="default" className="ml-1">
          AI interpretation
        </Badge>
      </div>
      <p className="mb-4 text-sm text-muted-foreground">
        Generated by AI from the measured findings above. Always verify against
        the evidence — this is interpretation, not measured data.
      </p>

      <div className="space-y-8">
        {ROADMAP_ORDER.filter((b) => groups.has(b)).map((bucket) => (
          <div key={bucket}>
            <h3 className="mb-3 text-sm font-semibold text-muted-foreground">
              {bucket === "OTHER" ? "Other" : ROADMAP_LABEL[bucket]}
            </h3>
            <div className="space-y-4">
              {groups.get(bucket)!.map((it) => {
                const meta = CATEGORY_META[it.category];
                return (
                  <Card
                    key={it.id}
                    className="border-l-4 border-l-primary/60 p-5"
                  >
                    <div className="flex flex-wrap items-center gap-2">
                      <Badge variant={PRIORITY_VARIANT[it.priority] ?? "warning"}>
                        {it.priority}
                      </Badge>
                      {meta && (
                        <Badge variant="secondary">
                          <Icon name={meta.icon} className="size-3" />
                          {meta.label}
                        </Badge>
                      )}
                      <span className="ml-auto text-xs text-muted-foreground">
                        Impact {it.impact} · Effort {it.effort}
                      </span>
                    </div>

                    <h4 className="mt-3 font-semibold">{it.title}</h4>

                    <dl className="mt-3 grid gap-3 text-sm sm:grid-cols-3">
                      <div>
                        <dt className="text-xs font-medium text-muted-foreground">
                          Problem
                        </dt>
                        <dd className="mt-0.5">{it.problem}</dd>
                      </div>
                      <div>
                        <dt className="text-xs font-medium text-muted-foreground">
                          Evidence
                        </dt>
                        <dd className="mt-0.5">{it.evidence}</dd>
                      </div>
                      <div>
                        <dt className="text-xs font-medium text-muted-foreground">
                          Recommendation
                        </dt>
                        <dd className="mt-0.5">{it.recommendation}</dd>
                      </div>
                    </dl>

                    {(it.beforeText || it.afterText) && (
                      <div className="mt-4 grid gap-3 text-sm sm:grid-cols-2">
                        {it.beforeText && (
                          <div className="rounded-md bg-poor/8 p-3">
                            <p className="text-xs font-medium text-muted-foreground">
                              Before
                            </p>
                            <p className="mt-1">{it.beforeText}</p>
                          </div>
                        )}
                        {it.afterText && (
                          <div className="rounded-md bg-good/8 p-3">
                            <p className="text-xs font-medium text-muted-foreground">
                              After
                            </p>
                            <p className="mt-1">{it.afterText}</p>
                          </div>
                        )}
                      </div>
                    )}

                    {it.rationale && (
                      <p className="mt-3 text-xs text-muted-foreground">
                        {it.rationale}
                      </p>
                    )}
                  </Card>
                );
              })}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
